### ISSUE TITLE
De-allocation of cusLB

### ISSUE THREAD

**Issue by mosdragon** [cuStinger/cuStingerAlg#5]
https://github.com/cuStinger/cuStingerAlg/blob/master/src/static_page_rank/pr.cu#L62
https://github.com/cuStinger/cuStingerAlg/blob/master/src/static_breadth_first_search/bfs_top_down.cu#L50
https://github.com/cuStinger/cuStingerAlg/blob/master/src/static_connected_components/cc_load_balanced.cu#L42

allocated with:
`cusLB = new cusLoadBalance(custing,false,true);`

de-allocated with:
`free(cusLB);`

Should be: `delete cusLB;`

**Comment by mosdragon** [comment]
I actually attempted to resolve this on my branch: 
https://github.com/mosdragon/cuStingerAlg/tree/mem_manage_bug

However, this ended up breaking the cus-alg-tester.

```
$ ./cus-alg-tester ~/data/alok/jazz.graph Vertices: 199    Edges: 5484
The number of iterations           : 2
The number of connected-compoents  : 1
Total time for connected-compoents : 0.000205728
The number of levels          : 5
The number of elements found  : 198
Total time for BFS - Top-Down : 0.000720576
CUDA Error = 17: invalid device pointer from file /home/osamasakhi/cuStingerAlg/externals/cuStinger/src/alloc.cu, line 32
```

**Comment by ogreen** [comment]
So it could be that the LoadBalanceArray destructor is screwing things up.
Can you see where it is crashing in that class?

**Comment by ogreen** [comment]
This will be changed in the upcoming Version 2.0. We will no longer require the cusLoadBalance class.
